version: '3.9'

services:
    rolodex:        
        build:
            context: ./
        
        ports:
            - "3000:3000"

        volumes:
            - ./src:/app/src
            - ./public:/app/public
